# Generated by Django 5.1.4 on 2024-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='private_key',
            field=models.CharField(max_length=128),
        ),
    ]
